# Generated by Django 2.2 on 2019-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordData',
            fields=[
                ('topic', models.CharField(max_length=30)),
                ('word', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=30)),
                ('sentence', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
